BASE_URL = 'https://qa-scooter.praktikum-services.ru/api/v1'
CREATE_COURIER_URL = f'{BASE_URL}/courier'
LOGIN_COURIER_URL = f'{BASE_URL}/courier/login'
DELETE_COURIER_URL = f'{BASE_URL}/courier/:id'
ORDER_URL = f'{BASE_URL}/orders'